/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicundi.vista;

/**
 *
 * @author paola
 */
public class VCalculadora extends java.awt.Frame {

    /**
     * Creates new form VCalculadora
     */
    public VCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelValor1 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnCorrer = new javax.swing.JButton();
        LabelResult = new javax.swing.JLabel();
        lbResultado = new javax.swing.JLabel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(547, 55));
        jPanel1.setPreferredSize(new java.awt.Dimension(721, 60));

        LabelValor1.setForeground(new java.awt.Color(255, 255, 255));
        LabelValor1.setText("Valor");
        LabelValor1.setPreferredSize(new java.awt.Dimension(30, 20));
        jPanel1.add(LabelValor1);

        txtValor.setMinimumSize(new java.awt.Dimension(80, 20));
        txtValor.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel1.add(txtValor);

        btnCorrer.setBackground(new java.awt.Color(255, 0, 51));
        btnCorrer.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 11)); // NOI18N
        btnCorrer.setForeground(new java.awt.Color(255, 255, 255));
        btnCorrer.setText("Convertir");
        btnCorrer.setActionCommand("BSumar");
        jPanel1.add(btnCorrer);
        btnCorrer.getAccessibleContext().setAccessibleName("Convertir");

        LabelResult.setForeground(new java.awt.Color(255, 255, 255));
        LabelResult.setText("Resultado");
        jPanel1.add(LabelResult);

        lbResultado.setForeground(new java.awt.Color(255, 255, 255));
        lbResultado.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel1.add(lbResultado);

        add(jPanel1, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCalculadora().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel LabelResult;
    public javax.swing.JLabel LabelValor1;
    public javax.swing.JButton btnCorrer;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel lbResultado;
    public javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
}
