/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.unicundi.vista;

/**
 *
 * @author paola
 */
public class VCalculadora extends java.awt.Frame {

    /**
     * Creates new form VCalculadora
     */
    public VCalculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LabelValor1 = new javax.swing.JLabel();
        TextValor1 = new javax.swing.JTextField();
        LabelValo2 = new javax.swing.JLabel();
        TextValor2 = new javax.swing.JTextField();
        LabelResult = new javax.swing.JLabel();
        LabelResultado = new javax.swing.JLabel();
        BSumar = new javax.swing.JButton();
        BResta = new javax.swing.JButton();
        BMultiplicacion = new javax.swing.JButton();
        BDivision = new javax.swing.JButton();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        LabelValor1.setText("Valor 1");
        jPanel1.add(LabelValor1);

        TextValor1.setMinimumSize(new java.awt.Dimension(80, 20));
        TextValor1.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel1.add(TextValor1);

        LabelValo2.setText("Valor 2");
        jPanel1.add(LabelValo2);

        TextValor2.setPreferredSize(new java.awt.Dimension(80, 20));
        jPanel1.add(TextValor2);

        LabelResult.setText("Resultado");
        jPanel1.add(LabelResult);
        jPanel1.add(LabelResultado);

        BSumar.setText("Sumar");
        BSumar.setActionCommand("BSumar");
        jPanel1.add(BSumar);

        BResta.setText("Restar");
        jPanel1.add(BResta);

        BMultiplicacion.setText("Multiplicacion");
        jPanel1.add(BMultiplicacion);

        BDivision.setText("División");
        jPanel1.add(BDivision);

        add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VCalculadora().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BDivision;
    public javax.swing.JButton BMultiplicacion;
    public javax.swing.JButton BResta;
    public javax.swing.JButton BSumar;
    public javax.swing.JLabel LabelResult;
    public javax.swing.JLabel LabelResultado;
    public javax.swing.JLabel LabelValo2;
    public javax.swing.JLabel LabelValor1;
    public javax.swing.JTextField TextValor1;
    public javax.swing.JTextField TextValor2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
